POST http://localhost:5000/api/project/add-project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRjMjcwMDQ5YjQzZTUyOWE2YmQ2NmEiLCJpYXQiOjE2NjU5MzUxMDV9.snuTxZ-xYBLoJErxx9cv70Wlsr3lcDd_djVuEcI60Zs

{
  "name":"Marketing & Sales",
  "descreption":"This is descreption",
  "avatar":"https://pyxis.nymag.com/v1/imgs/d6a/dc7/4a5001b7beea096457f480c8808572428b-09-roll-safe.rsquare.w700.jpg",
  "category":"Marketing",
  "members":["634c270049b43e529a6bd66a","634b88de0cdfbbead5591c0a","634b89030cdfbbead5591c0d"]
}

###

GET http://localhost:5000/api/project/recent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRjMjcwMDQ5YjQzZTUyOWE2YmQ2NmEiLCJpYXQiOjE2NjU5MzUxMDV9.snuTxZ-xYBLoJErxx9cv70Wlsr3lcDd_djVuEcI60Zs

###
PATCH  http://localhost:5000/api/project/change-favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRiODhkZTBjZGZiYmVhZDU1OTFjMGEiLCJpYXQiOjE2NjU5ODk3MTN9.sxwPewxrsvONsRO75K2kKXvbSLeU6XwBZyq-sC2d-XI

{
  "idProject":"634ccea02fe35d8082f2a286"
}
###
GET http://localhost:5000/api/project/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRjMjcwMDQ5YjQzZTUyOWE2YmQ2NmEiLCJpYXQiOjE2NjU5MzUxMDV9.snuTxZ-xYBLoJErxx9cv70Wlsr3lcDd_djVuEcI60Zs
